-- Script DDL para criação das tabelas do sistema Fintech
-- Oracle Database - FIAP
-- Criado para RM557347

-- ============================================
-- SEQUENCES
-- ============================================

-- Sequence para TB_USUARIO
CREATE SEQUENCE SEQ_USUARIO START
WITH
    1 INCREMENT BY 1 NOMAXVALUE NOCYCLE CACHE 20;

-- Sequence para TB_TRANSACAO
CREATE SEQUENCE SEQ_TRANSACAO START
WITH
    1 INCREMENT BY 1 NOMAXVALUE NOCYCLE CACHE 20;

-- Sequence para TB_INVESTIMENTO
CREATE SEQUENCE SEQ_INVESTIMENTO START
WITH
    1 INCREMENT BY 1 NOMAXVALUE NOCYCLE CACHE 20;

-- Sequence para TB_META_FINANCEIRA
CREATE SEQUENCE SEQ_META_FINANCEIRA START
WITH
    1 INCREMENT BY 1 NOMAXVALUE NOCYCLE CACHE 20;

-- ============================================
-- TABELAS
-- ============================================

-- Tabela de Usuários
CREATE TABLE TB_USUARIO (
    ID_USUARIO NUMBER PRIMARY KEY,
    NOME_COMPLETO VARCHAR2 (100) NOT NULL,
    EMAIL VARCHAR2 (100) NOT NULL UNIQUE,
    SENHA VARCHAR2 (255) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    GENERO VARCHAR2 (20) NOT NULL,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ULTIMO_LOGIN TIMESTAMP,
    ATIVO CHAR(1) DEFAULT 'S' NOT NULL CHECK (ATIVO IN ('S', 'N'))
);

-- Tabela de Transações
CREATE TABLE TB_TRANSACAO (
    ID_TRANSACAO NUMBER PRIMARY KEY,
    ID_USUARIO NUMBER NOT NULL,
    TIPO_TRANSACAO VARCHAR2 (20) NOT NULL CHECK (
        TIPO_TRANSACAO IN (
            'CREDITO',
            'DEBITO',
            'TRANSFERENCIA'
        )
    ),
    CATEGORIA VARCHAR2 (50) NOT NULL,
    DESCRICAO VARCHAR2 (255),
    VALOR NUMBER (12, 2) NOT NULL CHECK (VALOR > 0),
    DATA_TRANSACAO DATE NOT NULL,
    CONSTRAINT FK_TRANSACAO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO (ID_USUARIO)
);

-- Tabela de Investimentos
CREATE TABLE TB_INVESTIMENTO (
    ID_INVESTIMENTO NUMBER PRIMARY KEY,
    ID_USUARIO NUMBER NOT NULL,
    TIPO VARCHAR2 (30) NOT NULL CHECK (
        TIPO IN (
            'CDB',
            'TESOURO_DIRETO',
            'TESOURO_SELIC',
            'TESOURO_IPCA',
            'LCI',
            'LCA',
            'POUPANCA',
            'FUNDO_DI',
            'FUNDO_RENDA_FIXA',
            'FUNDO_MULTIMERCADO',
            'ACAO',
            'FII',
            'ETF',
            'CRIPTO'
        )
    ),
    VALOR_INVESTIDO NUMBER (14, 2) NOT NULL CHECK (VALOR_INVESTIDO > 0),
    DATA_APLICACAO DATE NOT NULL,
    DATA_RESGATE DATE,
    CONSTRAINT FK_INVESTIMENTO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO (ID_USUARIO),
    CONSTRAINT CK_DATA_RESGATE CHECK (
        DATA_RESGATE IS NULL
        OR DATA_RESGATE >= DATA_APLICACAO
    )
);

-- Tabela de Metas Financeiras
CREATE TABLE TB_META_FINANCEIRA (
    ID_META NUMBER PRIMARY KEY,
    ID_USUARIO NUMBER NOT NULL,
    NOME VARCHAR2 (100) NOT NULL,
    DESCRICAO VARCHAR2 (255),
    CATEGORIA VARCHAR2 (20) NOT NULL CHECK (
        CATEGORIA IN (
            'VIAGEM',
            'CASA',
            'CARRO',
            'EDUCACAO',
            'SAUDE',
            'EMERGENCIA',
            'APOSENTADORIA',
            'INVESTIMENTO',
            'CASAMENTO',
            'FESTA',
            'ELETRONICOS',
            'REFORMA',
            'DIVIDA',
            'NEGOCIO',
            'RESERVA',
            'LAZER',
            'OUTROS'
        )
    ),
    VALOR_NECESSARIO NUMBER (14, 2) NOT NULL CHECK (VALOR_NECESSARIO > 0),
    VALOR_ACUMULADO NUMBER (14, 2) DEFAULT 0 NOT NULL CHECK (VALOR_ACUMULADO >= 0),
    DATA_LIMITE DATE,
    DATA_CRIACAO DATE DEFAULT SYSDATE NOT NULL,
    STATUS VARCHAR2 (15) DEFAULT 'ATIVA' NOT NULL CHECK (
        STATUS IN (
            'ATIVA',
            'PAUSADA',
            'CONCLUIDA',
            'VENCIDA',
            'CANCELADA'
        )
    ),
    CONSTRAINT FK_META_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO (ID_USUARIO),
    CONSTRAINT CK_VALOR_ACUMULADO_META CHECK (
        VALOR_ACUMULADO <= VALOR_NECESSARIO
        OR STATUS = 'CONCLUIDA'
    )
);

-- Tabela de Configurações do Usuário
CREATE TABLE TB_CONFIG_USUARIO (
    ID_USUARIO NUMBER PRIMARY KEY,
    MOEDA_PADRAO VARCHAR2 (5) DEFAULT 'BRL' NOT NULL CHECK (
        MOEDA_PADRAO IN (
            'BRL',
            'USD',
            'EUR',
            'GBP',
            'JPY',
            'CAD',
            'AUD',
            'CHF',
            'CNY',
            'ARS',
            'CLP',
            'MXN',
            'COP',
            'PEN',
            'UYU'
        )
    ),
    NOTIFICACOES_ATIVAS VARCHAR2 (3) DEFAULT 'SIM' NOT NULL CHECK (
        NOTIFICACOES_ATIVAS IN ('SIM', 'NAO')
    ),
    TEMA_ESCURO VARCHAR2 (3) DEFAULT 'NAO' NOT NULL CHECK (TEMA_ESCURO IN ('SIM', 'NAO')),
    NOTIFICACAO_EMAIL VARCHAR2 (3) DEFAULT 'SIM' NOT NULL CHECK (
        NOTIFICACAO_EMAIL IN ('SIM', 'NAO')
    ),
    NOTIFICACAO_PUSH VARCHAR2 (3) DEFAULT 'SIM' NOT NULL CHECK (
        NOTIFICACAO_PUSH IN ('SIM', 'NAO')
    ),
    IDIOMA VARCHAR2 (5) DEFAULT 'pt_BR' NOT NULL,
    FORMATO_DATA VARCHAR2 (10) DEFAULT 'dd/MM/yyyy' NOT NULL,
    FUSO_HORARIO VARCHAR2 (50) DEFAULT 'America/Sao_Paulo',
    ULTIMA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_CONFIG_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO (ID_USUARIO)
);

-- ============================================
-- ÍNDICES PARA PERFORMANCE
-- ============================================

-- Índices para TB_USUARIO
CREATE INDEX IDX_USUARIO_EMAIL ON TB_USUARIO (EMAIL);

CREATE INDEX IDX_USUARIO_ATIVO ON TB_USUARIO (ATIVO);

CREATE INDEX IDX_USUARIO_DATA_CADASTRO ON TB_USUARIO (DATA_CADASTRO);

-- Índices para TB_TRANSACAO
CREATE INDEX IDX_TRANSACAO_USUARIO ON TB_TRANSACAO (ID_USUARIO);

CREATE INDEX IDX_TRANSACAO_DATA ON TB_TRANSACAO (DATA_TRANSACAO);

CREATE INDEX IDX_TRANSACAO_TIPO ON TB_TRANSACAO (TIPO_TRANSACAO);

CREATE INDEX IDX_TRANSACAO_CATEGORIA ON TB_TRANSACAO (CATEGORIA);

CREATE INDEX IDX_TRANSACAO_USUARIO_DATA ON TB_TRANSACAO (ID_USUARIO, DATA_TRANSACAO);

-- Índices para TB_INVESTIMENTO
CREATE INDEX IDX_INVESTIMENTO_USUARIO ON TB_INVESTIMENTO (ID_USUARIO);

CREATE INDEX IDX_INVESTIMENTO_TIPO ON TB_INVESTIMENTO (TIPO);

CREATE INDEX IDX_INVESTIMENTO_DATA_APLICACAO ON TB_INVESTIMENTO (DATA_APLICACAO);

CREATE INDEX IDX_INVESTIMENTO_DATA_RESGATE ON TB_INVESTIMENTO (DATA_RESGATE);

CREATE INDEX IDX_INVESTIMENTO_ATIVO ON TB_INVESTIMENTO (ID_USUARIO, DATA_RESGATE);

-- Índices para TB_META_FINANCEIRA
CREATE INDEX IDX_META_USUARIO ON TB_META_FINANCEIRA (ID_USUARIO);

CREATE INDEX IDX_META_STATUS ON TB_META_FINANCEIRA (STATUS);

CREATE INDEX IDX_META_CATEGORIA ON TB_META_FINANCEIRA (CATEGORIA);

CREATE INDEX IDX_META_DATA_LIMITE ON TB_META_FINANCEIRA (DATA_LIMITE);

CREATE INDEX IDX_META_USUARIO_STATUS ON TB_META_FINANCEIRA (ID_USUARIO, STATUS);

-- Índices para TB_CONFIG_USUARIO
CREATE INDEX IDX_CONFIG_MOEDA ON TB_CONFIG_USUARIO (MOEDA_PADRAO);

CREATE INDEX IDX_CONFIG_IDIOMA ON TB_CONFIG_USUARIO (IDIOMA);

CREATE INDEX IDX_CONFIG_NOTIFICACOES ON TB_CONFIG_USUARIO (NOTIFICACOES_ATIVAS);

-- ============================================
-- COMENTÁRIOS NAS TABELAS
-- ============================================

COMMENT ON
TABLE TB_USUARIO IS 'Tabela de usuários do sistema Fintech';

COMMENT ON COLUMN TB_USUARIO.ID_USUARIO IS 'Identificador único do usuário';

COMMENT ON COLUMN TB_USUARIO.EMAIL IS 'Email único do usuário para login';

COMMENT ON COLUMN TB_USUARIO.SENHA IS 'Hash SHA-256 da senha do usuário';

COMMENT ON COLUMN TB_USUARIO.ATIVO IS 'S=Ativo, N=Inativo';

COMMENT ON TABLE TB_TRANSACAO IS 'Tabela de transações financeiras';

COMMENT ON COLUMN TB_TRANSACAO.TIPO_TRANSACAO IS 'CREDITO=Receita, DEBITO=Despesa, TRANSFERENCIA=Transferência';

COMMENT ON COLUMN TB_TRANSACAO.VALOR IS 'Valor sempre positivo, tipo definido pela coluna TIPO_TRANSACAO';

COMMENT ON
TABLE TB_INVESTIMENTO IS 'Tabela de investimentos do usuário';

COMMENT ON COLUMN TB_INVESTIMENTO.DATA_RESGATE IS 'NULL=Investimento ativo, preenchido=Investimento resgatado';

COMMENT ON
TABLE TB_META_FINANCEIRA IS 'Tabela de metas financeiras dos usuários';

COMMENT ON COLUMN TB_META_FINANCEIRA.STATUS IS 'ATIVA, PAUSADA, CONCLUIDA, VENCIDA, CANCELADA';

COMMENT ON
TABLE TB_CONFIG_USUARIO IS 'Tabela de configurações personalizadas do usuário';

-- ============================================
-- TRIGGERS PARA ATUALIZAÇÃO AUTOMÁTICA
-- ============================================

-- Trigger para atualizar ULTIMA_ATUALIZACAO em TB_CONFIG_USUARIO
CREATE OR REPLACE TRIGGER TRG_CONFIG_USUARIO_UPDATE
    BEFORE UPDATE ON TB_CONFIG_USUARIO
    FOR EACH ROW
BEGIN
    :NEW.ULTIMA_ATUALIZACAO := CURRENT_TIMESTAMP;
END;
/

-- Trigger para validar dados de TB_USUARIO
CREATE OR REPLACE TRIGGER TRG_USUARIO_VALIDATE
    BEFORE INSERT OR UPDATE ON TB_USUARIO
    FOR EACH ROW
BEGIN
    -- Valida email
    IF NOT REGEXP_LIKE(:NEW.EMAIL, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$') THEN
        RAISE_APPLICATION_ERROR(-20001, 'Email inválido');
    END IF;
    
    -- Valida idade mínima (16 anos)
    IF :NEW.DATA_NASCIMENTO > ADD_MONTHS(SYSDATE, -16*12) THEN
        RAISE_APPLICATION_ERROR(-20002, 'Usuário deve ter pelo menos 16 anos');
    END IF;
    
    -- Define data de cadastro se não informada
    IF :NEW.DATA_CADASTRO IS NULL THEN
        :NEW.DATA_CADASTRO := CURRENT_TIMESTAMP;
    END IF;
END;
/

-- ============================================
-- DADOS INICIAIS PARA TESTES (OPCIONAL)
-- ============================================

-- Inserir usuário de teste (senha: 123456 - hash SHA-256)
INSERT INTO
    TB_USUARIO (
        ID_USUARIO,
        NOME_COMPLETO,
        EMAIL,
        SENHA,
        DATA_NASCIMENTO,
        GENERO,
        ATIVO
    )
VALUES (
        SEQ_USUARIO.NEXTVAL,
        'Usuário Teste',
        'teste@fiap.com.br',
        'e10adc3949ba59abbe56e057f20f883e', -- Hash MD5 de '123456' (para teste apenas)
        TO_DATE ('1990-01-01', 'YYYY-MM-DD'),
        'MASCULINO',
        'S'
    );

-- Inserir configuração padrão para o usuário de teste
INSERT INTO
    TB_CONFIG_USUARIO (ID_USUARIO)
VALUES (SEQ_USUARIO.CURRVAL);

-- ============================================
-- VIEWS ÚTEIS PARA CONSULTAS
-- ============================================

-- View com resumo financeiro por usuário
CREATE OR REPLACE VIEW VW_RESUMO_USUARIO AS
SELECT
    u.ID_USUARIO,
    u.NOME_COMPLETO,
    u.EMAIL,
    COALESCE(receitas.TOTAL_RECEITAS, 0) AS TOTAL_RECEITAS,
    COALESCE(despesas.TOTAL_DESPESAS, 0) AS TOTAL_DESPESAS,
    COALESCE(receitas.TOTAL_RECEITAS, 0) - COALESCE(despesas.TOTAL_DESPESAS, 0) AS SALDO_ATUAL,
    COALESCE(
        investimentos.TOTAL_INVESTIDO,
        0
    ) AS TOTAL_INVESTIDO,
    COALESCE(metas.TOTAL_METAS_ATIVAS, 0) AS METAS_ATIVAS
FROM
    TB_USUARIO u
    LEFT JOIN (
        SELECT ID_USUARIO, SUM(VALOR) AS TOTAL_RECEITAS
        FROM TB_TRANSACAO
        WHERE
            TIPO_TRANSACAO = 'CREDITO'
        GROUP BY
            ID_USUARIO
    ) receitas ON u.ID_USUARIO = receitas.ID_USUARIO
    LEFT JOIN (
        SELECT ID_USUARIO, SUM(VALOR) AS TOTAL_DESPESAS
        FROM TB_TRANSACAO
        WHERE
            TIPO_TRANSACAO = 'DEBITO'
        GROUP BY
            ID_USUARIO
    ) despesas ON u.ID_USUARIO = despesas.ID_USUARIO
    LEFT JOIN (
        SELECT ID_USUARIO, SUM(VALOR_INVESTIDO) AS TOTAL_INVESTIDO
        FROM TB_INVESTIMENTO
        WHERE
            DATA_RESGATE IS NULL
        GROUP BY
            ID_USUARIO
    ) investimentos ON u.ID_USUARIO = investimentos.ID_USUARIO
    LEFT JOIN (
        SELECT
            ID_USUARIO,
            COUNT(*) AS TOTAL_METAS_ATIVAS
        FROM TB_META_FINANCEIRA
        WHERE
            STATUS = 'ATIVA'
        GROUP BY
            ID_USUARIO
    ) metas ON u.ID_USUARIO = metas.ID_USUARIO
WHERE
    u.ATIVO = 'S';

-- View de investimentos ativos
CREATE OR REPLACE VIEW VW_INVESTIMENTOS_ATIVOS AS
SELECT i.*, u.NOME_COMPLETO, TRUNC (SYSDATE - i.DATA_APLICACAO) AS DIAS_INVESTIDO
FROM
    TB_INVESTIMENTO i
    JOIN TB_USUARIO u ON i.ID_USUARIO = u.ID_USUARIO
WHERE
    i.DATA_RESGATE IS NULL
    AND u.ATIVO = 'S';

-- Índices para otimização

-- ============================================
-- GRANTS PARA O USUÁRIO DA APLICAÇÃO
-- ============================================

-- Conceder permissões para o usuário da aplicação (substitua RM557347 pelo seu RM)
-- GRANT SELECT, INSERT, UPDATE, DELETE ON TB_USUARIO TO RM557347;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON TB_TRANSACAO TO RM557347;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON TB_INVESTIMENTO TO RM557347;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON TB_META_FINANCEIRA TO RM557347;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON TB_CONFIG_USUARIO TO RM557347;
-- GRANT SELECT ON SEQ_USUARIO TO RM557347;
-- GRANT SELECT ON SEQ_TRANSACAO TO RM557347;
-- GRANT SELECT ON SEQ_INVESTIMENTO TO RM557347;
-- GRANT SELECT ON SEQ_META_FINANCEIRA TO RM557347;

COMMIT;